version: '2'

volumes:
  frontend_data:
  Frontend_data:
  db_data:

services:
  uxdb:
    image: postgres:latest
    container_name: uxdb
    restart: always
    ports:
      - "5432:5432"
    environment:
      - "POSTGRES_DB=uxbox"
      - "POSTGRES_USER=uxbox"
      - "POSTGRES_PASSWORD=uxbox_postgres_password"
    volumes:
      - db_data:/var/lib/postgresql/data
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro

  uxbackend:
    #build: ./
    image: monogramm/docker-uxbox-frontend
    container_name: uxbackend
    #restart: always
    depends_on:
      - uxdb
    ports:
      - 6060:6060
    environment:
      # HTTP setup
      - UXBOX_HTTP_SERVER_DEBUG=false
      - UXBOX_MEDIA_URI="/media/"
      #- UXBOX_MEDIA_URI="http://uxbox.io/media/"
      - UXBOX_MEDIA_DIRECTORY="resources/public/media"
      - UXBOX_ASSETS_URI="/static/"
      #- UXBOX_ASSETS_URI="http://uxbox.io/static/"
      - UXBOX_ASSETS_DIRECTORY="resources/public/static"
      # Database setup
      - UXBOX_DATABASE_USERNAME="uxbox"
      - UXBOX_DATABASE_PASSWORD="uxbox_postgres_password"
      - UXBOX_DATABASE_NAME="uxbox"
      - UXBOX_DATABASE_SERVER="uxdb"
      - UXBOX_DATABASE_PORT=5432
      # Mail setup
      - UXBOX_EMAIL_REPLY_TO="no-reply@uxbox.io"
      - UXBOX_EMAIL_FROM="no-reply@uxbox.io"
      # STMP setup
      - UXBOX_SMTP_HOST="localhost"
      - UXBOX_SMTP_PORT=25
      - UXBOX_SMTP_USER="uxbox"
      - UXBOX_SMTP_PASSWORD="youshouldoverwritethiswithsomethingelse"
      - UXBOX_SMTP_SSL=false
      - UXBOX_SMTP_TLS=false
      - UXBOX_SMTP_ENABLED=false
      # Security setup
      - UXBOX_SECRET=""
    volumes:
      - /srv/uxbox/Frontend/resources:/srv/uxbox/resources
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro

  uxbackend:
    build: ./
    #image: monogramm/uxbox:frontend
    container_name: uxbackend
    #hostname: uxbox.io
    #restart: always
    depends_on:
      - uxbackend
    ports:
      - 80:80
    environment:
      - UXBOX_CONFIG_URL="http://localhost:6060/api/"
      #- UXBOX_CONFIG_URL="http://uxbox.io/api/"
    volumes:
      #- /srv/uxbox/frontend/html:/usr/share/nginx/html
      - /srv/uxbox/Frontend/resources:/srv/uxbox/resources:ro
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
