version: '2.3'

volumes:
  db_data:
  backend_data:
  backend_m2:
  frontend_data:

services:
  # https://docs.docker.com/docker-hub/builds/automated-testing/
  sut:
    build:
      context: ./test
      dockerfile: Dockerfile
    command: sh /docker_test.sh
    depends_on:
      - uxbox_db
      - uxbox_mailer
      - uxbox_backend
      - uxbox_frontend
    environment:
      - DOCKER_TEST_CONTAINER=uxbox_frontend
    volumes_from:
      - uxbox_backend
      - uxbox_frontend
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro

  uxbox_db:
    image: postgres:alpine
    container_name: uxbox_db
    restart: always
    stop_signal: SIGINT
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${UXBOX_DB_LOGIN}", "-d", "${UXBOX_DB_NAME}"]
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    environment:
      - POSTGRES_INITDB_ARGS="--data-checksums"
      - POSTGRES_DB=${UXBOX_DB_NAME}
      - POSTGRES_USER=${UXBOX_DB_LOGIN}
      - POSTGRES_PASSWORD=${UXBOX_DB_PASSWD}

  uxbox_mailer:
    image: sj26/mailcatcher:latest
    hostname: uxbox_mailer
    container_name: uxbox_mailer
    restart: always
    expose:
      - 1025
    ports:
      - "1080:1080"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro

  uxbox_backend:
    #build: ./
    image: monogramm/docker-uxbox-backend:develop
    container_name: uxbox_backend
    #restart: always
    depends_on:
      uxbox_db:
        condition: service_healthy
      uxbox_mailer:
        condition: service_started
      uxbox_redis:
        condition: service_healthy
    ports:
      - "3447:3447"
      - "3448:3448"
      - "3449:3449"
      - "6060:6060"
      - "9090:9090"
    volumes:
      - backend_data:/srv/uxbox/resources
      - backend_m2:/root/.m2
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    environment:
      # HTTP setup
      - UXBOX_HTTP_SERVER_PORT=6060
      - UXBOX_HTTP_SERVER_DEBUG=false
      # Database setup (with base DB properties or full JDBC URI)
      - UXBOX_DATABASE_SERVER=uxbox_db
      - UXBOX_DATABASE_PORT=5432
      #- UXBOX_DATABASE_URI=jdbc:postgresql://uxbox_db:5432/${UXBOX_DB_NAME}
      - UXBOX_DATABASE_NAME=${UXBOX_DB_NAME}
      - UXBOX_DATABASE_USERNAME=${UXBOX_DB_LOGIN}
      - UXBOX_DATABASE_PASSWORD=${UXBOX_DB_PASSWD}
      # Redis setup
      - UXBOX_REDIS_URI=redis://uxbox_redis/0
      # Media setup
      - UXBOX_MEDIA_DIRECTORY=resources/public/media
      - UXBOX_MEDIA_URI=/media/
      #- UXBOX_MEDIA_URI=http://${UXBOX_WEB_DOMAIN}/media/
      # Assets setup
      - UXBOX_ASSETS_DIRECTORY=resources/public/static
      - UXBOX_ASSETS_URI=/static/
      #- UXBOX_ASSETS_URI=http://${UXBOX_WEB_DOMAIN}/static/
      # Mail setup
      - UXBOX_EMAIL_REPLY_TO=no-reply@${UXBOX_WEB_DOMAIN}
      - UXBOX_EMAIL_FROM=no-reply@${UXBOX_WEB_DOMAIN}
      # STMP setup
      - UXBOX_SMTP_HOST=uxbox_mailer
      - UXBOX_SMTP_PORT=1025
      - UXBOX_SMTP_USER=${UXBOX_SMTP_USER}
      - UXBOX_SMTP_PASSWORD=${UXBOX_SMTP_PWD}
      - UXBOX_SMTP_SSL=false
      - UXBOX_SMTP_TLS=false
      - UXBOX_SMTP_ENABLED=true
      # Security setup
      - UXBOX_REGISTRATION_ENABLED=true
      - UXBOX_SECRET="${UXBOX_SECRET}

  uxbox_redis:
    image: redis:6.0-rc3
    hostname: $UXBOX_WEB_DOMAIN
    container_name: uxbox_redis
    restart: always
    ports:
      - 6379:6379

  uxbox_frontend:
    build: ./
    #image: monogramm/docker-uxbox-frontend:latest
    container_name: uxbox_frontend
    hostname: $UXBOX_WEB_DOMAIN
    #restart: always
    depends_on:
      - uxbox_backend
    ports:
      - 80:80
    volumes:
      #- frontend_data:/usr/share/nginx/html
      - backend_data:/srv/uxbox/resources/public:ro
      # If you want, you can overwrite the provided default NGINX config
      #- ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      # You can also add certificates for SSL connection
      #- ./nginx/server.crt:/etc/nginx/keys/server.crt
      #- ./nginx/server.key:/etc/nginx/keys/server.key
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    environment:
      # No quotes here!
      - UXBOX_PUBLIC_URI=http://localhost/
      - UXBOX_GOOGLE_CLIENT_ID=true
      - UXBOX_LOGIN_WITH_LDAP=false
      # Only used at build time
      - UXBOX_DEMO_WARNING=true
      - UXBOX_DEPLOY_DATE=""
      - UXBOX_DEPLOY_COMMIT=""
      - UXBOX_DEBUG=false
