#!/bin/bash

# See documentation for details:
# https://docs.docker.com/docker-hub/builds/advanced/

echo 'Download custom assets...'
# TODO Download custom assets to test loading of images and icons
