
name: Docker Image CI

on:
  pull_request:
  push:
    branches:
      - main
      - master
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: ['1.5', '1.6', 'develop', 'main', ]
        variant: ['alpine', 'mainline']

    steps:
      - name: Check Out Repo
        uses: actions/checkout@v2

      - name: Execute CI hooks
        id: docker_build
        run: |
          cd ./images/${{ matrix.version }}/${{ matrix.variant }}/
          ./hooks/run

      - name: Display docker images
        run: docker images
