
name: Docker Image CI

on:
  push:
    branches:
      - master
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: ['1.0', 'main', 'develop']
        variant: ['alpine', 'mainline']

    steps:
      - name: Check Out Repo
        uses: actions/checkout@v2

      - name: Execute CI hooks
        id: docker_build
        run: |
          cd ./images/${{ matrix.version }}/${{ matrix.variant }}/
          ./hooks/run

      - name: docker images
        run: docker images
